version: "3.1"

services:
  rg-api:
    build: "./../rg-api"
    depends_on:
      - rg-mongo
    command:
      ["./wait-for-it/wait-for-it.sh", "rg-mongo_1:27017", "--", "npm", "start"]
    ports:
      - "3001:3001"
    volumes:
      - ./../rg-api:/usr/src/app
    networks:
      - rg-net
    environment:
      - NODE_ENV=development
      - CUSTOM_PORT=3001
    secrets:
      - JWT_SECRET
      - CORS_WHITELIST
  rg-admin:
    build: "./../rg-admin"
    depends_on:
      - rg-mongo
      - rg-api
    ports:
      - "8080:8080"
    volumes:
      - ./../rg-admin:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - rg-net
  rg-graphql:
    build: "./../rg-graphql"
    depends_on:
      - rg-mongo
      - rg-api
    ports:
      - "4000:4000"
    volumes:
      - ./../rg-graphql:/usr/src/app
    networks:
      - rg-net
    environment:
      - API_URL=http://best-chile_rg-api_1:3001/api
      - SUPER_AUTH_TOKEN=Bearer\ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjNiZThkZWM2YmI4ZTJkODJlNmZjNmIiLCJlbWFpbCI6InN1cGVyQHVzZXIuY29tIiwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoic3VwZXIiLCJleHBpcmF0aW9uIjoxNTM1MDY0NzExLCJpYXQiOjE1MzI0NzI3MTF9.WCCR_OL5cZCv-MiROCc-FyOi2ppbuSg0mSu9Wd5Phx0
      - ADMIN_AUTH_TOKEN=Bearer\ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YjFmNGVmZGI0NGJkMWZlMmE1ZGVhNzkiLCJlbWFpbCI6ImFkbWludXNlckBsYWxhbGEuY29tIiwidXNlcm5hbWUiOiJhZG1pbnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJleHBpcmF0aW9uIjoxNTMxNDIwNjM5LCJpYXQiOjE1Mjg4Mjg2Mzl9.U6Ku8U42fn84u8lFScx4xvWo8Zz_KoAEppGAScleB5g
      - DEFAULT_AUTH_TOKEN=Bearer\ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Yjk5MzBlMWFkYTZmOTU0OGM0ZjhhYWYiLCJlbWFpbCI6ImRlZmF1bHRAdXNlci5jb20iLCJ1c2VybmFtZSI6ImRlZmF1bHR1c2VyIiwicm9sZSI6ImRlZmF1bHQiLCJleHBpcmF0aW9uIjoxNTM5MzU4MTc3LCJpYXQiOjE1MzY3NjYxNzd9.iUBkNmPZHBvd_qz77NkOVFjNcgGjjMQl7-uoztkI82I
  rg-client:
    build: "./../rg-client"
    depends_on:
      - rg-graphql
    ports:
      - "3000:3000"
    volumes:
      - ./../rg-client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GRAPHQL_URL=http://localhost:4000/graphql
    networks:
      - rg-net
  rg-mongo:
    # TODO: Need to flesh this out a bit. Is it the right image? user/pass, etc
    image: "bitnami/mongodb:3.6"
    ports:
      - "27017:27017"
    volumes:
      - rg-mongo-data:/data/db
      - rg-mongo-config-data:/data/configdb
    networks:
      - rg-net
volumes:
  rg-mongo-data:
  rg-mongo-config-data:

networks:
  rg-net:

secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  CORS_WHITELIST:
    file: ./secrets/CORS_WHITELIST
