version: "3.1"

services:
  rg-api:
    build: "./../rg-api"
    depends_on:
      - rg-mongo
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "rg-mongo_1:27017",
        "--",
        "npm",
        "start",
      ]
    ports:
      - "3000:3000"
    volumes:
      - ./../rg-api:/usr/src/app
    networks:
      - rg-net
    environment:
      - NODE_ENV=development
    secrets:
      - JWT_SECRET
      - CORS_WHITELIST
  rg-admin:
    build: "./../rg-admin"
    depends_on:
      - rg-mongo
      - rg-api
    ports:
      - "8080:8080"
    volumes:
      - ./../rg-admin:/usr/src/app
    networks:
      - rg-net
  rg-graphql:
    build: "./../rg-graphql"
    depends_on:
      - rg-mongo
      - rg-api
    ports:
      - "4000:4000"
    volumes:
      - ./../rg-graphql:/usr/src/app
    networks:
      - rg-net
  rg-client:
    build: "./../rg-client"
    depends_on:
      - rg-graphql
    ports:
      - "3001:3001"
    volumes:
      - ./../rg-client:/usr/src/app
    networks:
      - rg-net
  rg-mongo:
    # TODO: Need to flesh this out a bit. Is it the right image? user/pass, etc
    image: "bitnami/mongodb:3.6"
    ports:
      - "27017:27017"
    volumes:
      - rg-mongo-data:/data/db
      - rg-mongo-config-data:/data/configdb
    networks:
      - rg-net
volumes:
  rg-mongo-data:
  rg-mongo-config-data:

networks:
  rg-net:

secrets:
  JWT_SECRET:
    file: ./secrets/JWT_SECRET
  CORS_WHITELIST:
    file: ./secrets/CORS_WHITELIST
